### ISSUE TITLE
Introduce one extra layer for the cache-folder

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#1]
Currently all "cache" objects are stored directly in the root of the cache folder. This works just fine, but can be a bit cumbersome to "manage"/browse when having a large amount of images. I have about ~50k images in the gallery, and this results in about 250k files in the cache folder (making basic browsing with "ls" commands etc a bit cumbersome).

Suggestion; put all cache files related to an album (thumbnails + json), within a folder bearing the same name, that is placed in the cache folder.

Example; given a cache file with the name ```this_is_a_test_folder_with_spaces-img_6454.jpg_150s.jpg```. 
Current path: ```$webroot/cache/this_is_a_test_folder_with_spaces*```
New path: ```$webroot/cache/this_is_a_test_folder_with_spaces/this_is_a_test_folder_with_spaces*```

If you have nested albums, it would be sufficient to put them all in the same folder.

**Comment by jallakim** [comment]
(I'm just putting old "future enhancement ideas" on the paper now that we have a GitHub (-: )

**Comment by paolobenve** [comment]
I had thought about something this problem, too. I have 38k photos, and I'm afraid that some day I'm going to reach the os limit.

My idea was to implement a folder structure based on md5: calculate md4 of the path+name or of cachepath and take the first two chars of it as folder name, this way chache will be subdivide into 256 folders

**Comment by jallakim** [comment]
That would make it somewhat hard to "locate" files manually?

How about using the first two characters of the album as the folder name? That would, theoretically, limit it to 26^2 folders (or some more if you count non-english characters), and also make it somewhat intuitive to locate the cached files (if you would like to alter/manage/delete/whatnot them), as you'd only need the album name to derive the folder.

**Comment by paolobenve** [comment]
done in cacheSubDirs branch

for a given photo, the thumbnails are put in a cache subfolders identified by the first two characters of the md5 of the image path+name, the subdir is saved in the json files so that it's retrieved easily

the json files carry the cache path of every photo, so that a js call is saved
