### ISSUE TITLE
"by_date"-links not consistent?

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#11]
Not sure if the "folders view"/"year view"/"month view"/"day view" is very consistent? 

I.e. when are which of them supposed to be displayed? They keep changing around without a clear pattern? It also seems that the number of links changes between one and two, depending on where you are (only one is shown when in "year view", but two for all the other modes).

**Comment by paolobenve** [comment]
I think a right floating button in title line would be better: it'd switch to by day view.

This way various link in metadata bar would disappear

**Comment by paolobenve** [comment]
top right button switching from folders to date view: ok

**Comment by jallakim** [comment]
@paolobenve, nice!

Maybe we should make that link a bit less intrusive/visible? I.e. make it "blend in" a bit more.. maybe make it part of the "path" that we display at the top of the page?

Example when in folders view:
> My photos » Folders » Somefolder » Somesubfolder » IMG_7561

Example when in date view:
> My photos » Date » Somefolder » Somesubfolder » IMG_7561

(where the "Folders" and "Date" text is an URL/clickable to switch between the two)
