### ISSUE TITLE
Display folder/albums as normal thumbnails

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#12]
Folders/albums when in the folder view should just be displayed as normal thumbnails (equal to the images). IMHO it only makes sense to make folders/albums and images distinguishable when in the dates view (where you can have both folders/albums and images in the same page).

**Comment by paolobenve** [comment]
the user can have both folders/albums and images in the same page, as in http://palmaro.qumran2.net/#!/_folders-chiesa

**Comment by jallakim** [comment]
Yes, but I was thinking only on the main folder page (where there should only be folders/albums?). Within albums/folders it would make sense to differentiate.

**Comment by paolobenve** [comment]
main folder can have both folders/albums and images, too

**Comment by paolobenve** [comment]
let's give the user the option to show albums as images or with a different css

**Comment by paolobenve** [comment]
this option goes to the js config file options
