### ISSUE TITLE
Make folder/album view default

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#13]
I like the folder/date switch feature, but I think the folder view should be default. If one needs "by date", you could just view an image, and then navigate from there (or provide a link to "by date" in the bottom of the page or similar). I would probably use the folder/album view 90% of the time, and that means one extra mouse click 90% of the time I visit the gallery.

**Comment by paolobenve** [comment]
good suggestion, I'm going to try to show the folders as default initial view

**Comment by paolobenve** [comment]
should be done
