### ISSUE TITLE
CSS-changes compared to original PhotoFloat

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#14]
Hi,

Compared to the "original" PhotoFloat, I'm not sure if I like the CSS-changes regarding font size (smaller some places), font colors (white vs. blue, and green for the image names), spacing between thumbnails, and showing image names in the album view (the minimalistic "show all thumbnails" w/o anything "extra" was kinda neat). Example in difference between color/font size can be seen in the screenshots in #4.

I guess it's a personal preference, and easily changeable, but it would probably an idea to see what most people prefer, and use that as the standard.

**Comment by paolobenve** [comment]
I was thinking on permitting different preferences like this with a simple class add to the body tag, so that css vary according to user preferences

**Comment by jallakim** [comment]
That would probably be the easiest, yes. Include a default "custom.css.dist" or something (with examples/default style), which people can rename to "custom.css", and we put that in .gitignore, so that personal changes isn't conflicting with whatever is pushed/changed via git.

**Comment by paolobenve** [comment]
the work in the options branch solves this issue: the user has the ability to go back to previous styling
