### ISSUE TITLE
Translation should not interfere with changes in git: give photofloat a config file

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#16]
Currently you need to comment out the translation-thingie (```011-translations.js```) from ```index.html``` in order for it not to translate. This causes issues when changing things in the git repo, or when updating and things have changed in ```index.html```.

```011-translations.js``` should be renamed to ```011-translations.js.dist``` or similar, and ```011-translations.js``` added to ```.gitignore```. This would leave it out of the logic in ```js-css-minify.sh```, causing it not to be included by-default, unless someone decides to copy/rename it to ```011-translations.js```.

**Comment by paolobenve** [comment]
Translations are now managed in a transparent way: index.html contains all possible translations as hidden tags, only one is activated by js according to browser language0

011-translations.js isn't neede any more

**Comment by jallakim** [comment]
@paolobenve, nice addition, but the issue is somewhat still the same; avoid conflicts with git. If I now *only* want English, I have to customize index.html, which will potentially lead to merge issues/conflicts in the future. Could you put the translation logic in a separate file (similar to what I did in PR #17), so that we can .gitignore it or similar without causing issues in the future?

**Comment by paolobenve** [comment]
I don't understan: all intertationalized projects keep translations as part of the code, without git-ignoring them...

Due to the way the translations are put in index.html, one translation by line, merge conflicts seem unlikely

**Comment by jallakim** [comment]
@paolobenve, yeah, sure, but they usually keep the translation things as separate files, so that people can make local changes to them without (potentially) causing merge conflicts. They usually also have configuration files, which is typically named ```somefile.conf.dist``` or similar, and then they have ```somefile.conf``` in .gitignore (to avoid it being commited by a mistake) and people has to copy/rename the ```somefile.conf.dist``` to ```somefile.conf```, and then do the needed changes. That way local changes is ignored by git.

This project doesn't really need a configuration file, but somewhat the same approach should be done with things that require local changes (translations, theme/style, etc). In my case now, I really only want English translations, regardless of the browser language -- I cannot do this the way it's organized now, without doing large changes to index.html.

**Comment by paolobenve** [comment]
Maybe it would be better to put the translations in a js file, but I wouldn't ignore it. I'm seeing in `https://github.com/GNOME/gthumb/commits/master` that translations aren't git-ignored, and so I think it's in all similar projects.

Your need to choose the language independently of the browser's one: a solution could be an option `--language=xx` to `scanner/main.py`, which would make the py app include this info somewhere in the cache, in the same way it includes the thumbnails sizes, and js would follow this directive instead of using the browser language.

**Comment by jallakim** [comment]
Then I suggest we introduce a configuration file for PhotoFloat -- make it in JSON or something, so that both the frontend and backend (scanner) can use it. That config-file would have to be done in the way I explained. In that config, we could have a variable ```default_language``` or similar, and if set to ```auto```, it would use the browser preference. If set to ```en``` it would only translate to English, if set to ```it``` only Italian, etc. We then put the translations in a separate file, which will not be put into .gitignore.

This is done by multiple projects, where the configuration file ```configfile.conf.dist```(or similar) is added to git, while ```configfile.conf``` is added to .gitignore, so you need to rename/move it, so that you can have local changes without being tracked by git.

https://github.com/phppgadmin/phppgadmin/blob/master/conf/config.inc.php-dist
https://github.com/phpmyadmin/phpmyadmin/blob/master/config.sample.inc.php
https://github.com/digitalocean/netbox/blob/develop/netbox/netbox/configuration.example.py
https://github.com/librenms/librenms/blob/master/config.php.default
https://github.com/redmine/redmine/blob/master/config/configuration.yml.example
... and the list goes on (all where the config is in .gitignore, while an example config is included with another name).

**Comment by paolobenve** [comment]
ok, now I'm understanding! :-)

What are we putting into config file?

- thumbnails sizes
- language
- thumbnail spacing

What else?

**Comment by jallakim** [comment]
Not sure how to do style customisations in an easy way? Introduce some kind of templates for themes or similar? Not sure if thumbnail spacing/text colour/link sizes/image name under thumbnails/etc belongs would be feasible to put in a JSON configuration file? Maybe do a custom .css-file that is loaded last that could override the "default" settings? Not sure..

Other configuration file parameters;

- Cache path (so that you don't need to specify it as parameters to main.py all the time)
- Album path (same)
- Video/transcode bitrate (currently 4Mbps)

The ```floatapp```-thingie already has a configuration file, so we should probably make that use the same config at some point (I've never used the ```floatapp```, nor do I intend to use it).

**Comment by paolobenve** [comment]
style customization is easily made with jquery, don't worry!

Are you able to prepare the json file and make py and js read it?

**Comment by paolobenve** [comment]
other configuration parameters:

- "_folders" parameter
- "_by_date" parameter
- character to use in cache names as a substitution for "/": now it's "-", but a folder name with that character  inside it would produce an error
- page title to override hardcoded in index.html ("My photos")

**Comment by paolobenve** [comment]
more configuration parameters:

- make albums thumbnails diffferent from photo ones
- thumbnail generation: choose between cascading (image -> 1600 -> 1200 -> 800 -> 150) and parallel generation (all thumbnails generated from image)

**Comment by paolobenve** [comment]
More:

- show images names below them
- choose title font: large, medium, small
- title (folders + image name) colors
- image name color

**Comment by paolobenve** [comment]
More:

- jpeg quality for thumbnails
- background color
- title colors
- top right button text and background colors

**Comment by paolobenve** [comment]
instead of a json configuration file, I'd make a python one, which is simpler for the user

the scanner reads and uses it, and saves it as a json file for javascript, which loads and uses it

**Comment by jallakim** [comment]
Nice list. I'll start looking at this tomorrow (been away last part of last week + weekend).

I agree that Python configuration file, that generates a JSON-file, would be the best (I had the same thing in mind after giving it a bit of thought).

**Comment by paolobenve** [comment]
I already made the py part in a separate branch, I'm stuck with reading the json file by js

**Comment by paolobenve** [comment]
now js reads options

**Comment by paolobenve** [comment]
in order to use an arbitrary cache folder, options.json is stored in index.html's folder, and if it's read only, in cache path

In the same way, js begins searching it in index.html's folder, and if it doesn't find, in cache/

**Comment by jallakim** [comment]
Oh, you've done most of the work already. Good job (-:

Don't forget to do the whole ```Options.py.dist```-thingie, and add ```Options.py``` to ```./scanner/.gitignore```, and ```web/options.json``` + ```web/cache/options.json``` to ```./.gitignore```, before merging the commit to master (-:

**Comment by paolobenve** [comment]
`web/cache `is not in the repository, `web/options.json` isn't generated because `web` folder isn't (and must not be) writable by the web server

the user config file isn't in the repository, either. I personally keep it in `/etc/photofloat`

`Options.py` cannot be ignored, it only defines the default options and merges them with the user options given as argument to `main.py`

I added the sample config file, at its top it carries the instructions for use

**Comment by paolobenve** [comment]
all configuration variables are implemented

Please test!

Readme has to be modified, too

**Comment by jallakim** [comment]
Nice! Good work!

A few comments at the top of my head;

- ```web/options.json``` is still created by photofloat, so it's natural to have it in ```.gitignore```, as it's not something that should ever be added to the git repo.
- ```web/album``` and ```web/cache``` should also be added to ```.gitignore``` (as those are the default locations, and should never be added to the git repo)
- For the option file itself, you changed how you implemented it since yesterday (by having default values specified in ```ModOptions.py```, and being able to override them in the ```UserOptions.py```), and as such, this removes the need for anything within ```.gitignore``` for those files. I like the solution you came up with better (-:
- It seems that the web page doesn't respond well if it can't find ```options.json``. First time I loaded the page, it showed an error stating that "options.json is missing" or something, but refreshing (and disabling cache) only shows an empty page; the "PhotoFloat"-link is shown, as well as the previous/next image arrows, but that's it.

... I haven't really tested it yet, hopefully I'll get the time this weekend.

**Comment by paolobenve** [comment]
I reworked the config file using ConfigParser, but I had some problem, and I made some mess with the code...

Now the config file is a typical linux config file, with parameters like

`parameter = value`

ConfigParser ensures a simpler structure of the file

The main app can be invoked with the old style (2 parameters, albums and cache paths, all other parameters will be stuck on default values) or new: 1 parameter, the config file path, all parameters may be modified

**Comment by paolobenve** [comment]
let's test it before merging to master

**Comment by paolobenve** [comment]
branch cacheSubDirs received the merge from the options one: it implements subdirs and the new options system

**Comment by jallakim** [comment]
Found one error; the md5-logic is missing for transcoded videos (they are put in the root cache-folder).

**Comment by jallakim** [comment]
You could also look into "create extra level of folders" into an option (switch between "first two characters of md5sum" and "first two characters of the album/folder"). If not, I'll make a PR for it, as it's not really straight-forward to find the cache files for an album (w/o searching).

**Comment by jallakim** [comment]
The issue with missing md5-logic for transcoded images also makes the scanner delete the 150px thumbnail from the video in the same run as the thumbnail was created.

```
2017-06-26T18:18:44.464949   |  |  |--[processing image/video]                  IMG_7568.MOV
2017-06-26T18:18:45.984972   |  |  |  |--[thumbing]                                150, square
2017-06-26T18:18:46.108970   |  |  |  |--[150 thumbnail]                           OK
2017-06-26T18:18:46.109243   |  |  |  |--[transcoding]                             IMG_7568.MOV -> mp4, h264
2017-06-26T18:20:58.627047   |  |  |--[processing image/video]                  IMG_7944.MOV
2017-06-26T18:20:59.086634   |  |  |  |--[thumbing]                                150, square
2017-06-26T18:20:59.178604   |  |  |  |--[150 thumbnail]                           OK
2017-06-26T18:20:59.178885   |  |  |  |--[transcoding]                             IMG_7944.MOV -> mp4, h264
2017-06-26T18:23:48.778686   |  |--[cleanup]                                 searching for stale cache entries in subdir 90
2017-06-26T18:23:48.778867   |  |  |--[cleanup]                                 90/sørlandstur_31._juli-2._august_2015-img_7944.mov_150s.jpg
2017-06-26T18:23:48.779436   |  |--[cleanup]                                 searching for stale cache entries in subdir a3
2017-06-26T18:23:48.779619   |  |  |--[cleanup]                                 a3/osloltur_22-25._mai_2015-img_7568.mov_150s.jpg
2017-06-26T18:23:48.782954   |  |--[not deleting]                            osloltur_22-25._mai_2015-img_7568.mov.mp4
2017-06-26T18:23:48.783058   |  |--[not deleting]                            sørlandstur_31._juli-2._august_2015-img_7944.mov.mp4
```

**Comment by paolobenve** [comment]
No problem with the "first two characters of the album/folder" option , PR use welcome!

**Comment by paolobenve** [comment]
implemented the options to select which method to generate the 2-chars subdir, permitting not to use subdir, too

# the method to use for generating cache 2-charachters subdirs
# permitted values:
#    md5	: the leading 2 characters of the md5 of the image/video path relative to albums dir
#    folder	: the leading 2 characters of the subfolder of the image/video path relative to albums dir
#    (none)	: no subfolders
subdir_method =

**Comment by paolobenve** [comment]
the video thumbnail isn't deleted any more
