### ISSUE TITLE
Don't rethumb all files after interrupt

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#2]
We shouldn't have to rethumb/transcode all images/videos in an album if we interrupt photofloat mid-cycle. Currently, if ```main.py``` was half way through an album scan/run, hitting interrupt would cause you to start all over again for that album (even if ~50% of the thumbs/transcodes already was made, it would re-make them).

We should maybe check if file already exists (even if there is no .json-file), and if so, re-use it. Would probably have to do some kind of integrity check so that we don't get corrupt images, or scenarios where only 2 out of 4 thumbs of an image was created (in which we would have to re-make all the thumbs for that image).

**Comment by paolobenve** [comment]
I think that a ctl-c interrupt is already raised until the thumbnail is generated

currently it checks whether the thumbnail exists, how would we check for corruption? a json file with all the thumbnails md5?
