### ISSUE TITLE
social buttons

### ISSUE THREAD

**Issue by paolobenve** [paolobenve/photofloat#3]
I'd like to implement social share buttons, at least for facebook and twitter

the problem now is that if you share any photofloat page you are sharing the nude html.

We must solve two problems:

- look for a way to have a static page with at least the image: an url where the image is shown independently of js
- implement the buttons who share the correct url

In order to have the static url I was thinking in generating in cache folder an html page for each image, it could be the simple index.html where the img is inserted by python with a replace command

**Comment by jallakim** [comment]
Should probably be possible to solve a bit more dynamic? I.e. use the URL that we have to day (that directly links to the image, albeit via JS), and then just do some trickery to insert meta-tags or whatever it is that social media crawlers use to fetch "media" on available on the link. This would have to be done in order for video to be linked as well (where in-line showing of the video would be the ultimate goal).

**Comment by paolobenve** [comment]
the problem is that crawlers don't execute any js. Any meta-tags or whatever must be in the index.html page, or the page you share must have statically the image inside it

**Comment by paolobenve** [comment]
Give a try to https://github.com/cshold/social-sharing-buttons , it seems very simple: only a css and a js must be included

**Comment by paolobenve** [comment]
the solution:

- index.html -> index.php
- index.html/#!/album/media -> index.html?a=album&m=media/#!/album/media
- the share link in the share buttons will be index.html?a=album&m=media (without the hash)
- hashless index.html?a=album&m=media will make php to show the image, which will be detected by social media, and then redirect via js to index.html?a=album&m=media/#!/album/media (social media don't execute js)
- php code will detect hashless index.html&a=album&m=media to index.html&a=album&m=media/#!/album/media for normal viewing experience

**Comment by paolobenve** [comment]
implemented in master
