### ISSUE TITLE
Images "overflow" on the top

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#4]
Images seems to "overflow" on the top, going behind the album/path at the top.

Old behaviour:
![dump 2017-06-14 at 09 23 45](https://user-images.githubusercontent.com/359918/27120319-5ef22314-50e3-11e7-9d22-b58c6277ee67.png)

New behaviour:
![dump 2017-06-14 at 09 23 39](https://user-images.githubusercontent.com/359918/27120318-5eec957a-50e3-11e7-8d22-7d7adbb4042f.png)

Should be fixed so that it uses the old behaviour.

**Comment by paolobenve** [comment]
fixed
