### ISSUE TITLE
exclude folder from photofloat parsing

### ISSUE THREAD

**Issue by kosli** [paolobenve/photofloat#41]
is there a way that i could exclude certain folders, e.g. an idea would be to add a file ".photofloat.exclude" or so in a folder that shouldn't be scanned by photofloat. this would make it flexible and i wouldn't need to keep a central list of folders that should be excluded, but the information is "self-included".

**Comment by paolobenve** [comment]
implemented in master

**Comment by kosli** [comment]
OMG! You're my hero! So fast! Will test it tomorrow.
