### ISSUE TITLE
Use minified files?

### ISSUE THREAD

**Issue by jallakim** [paolobenve/photofloat#9]
Hi,

Why are we not using the minified .js/.css files in index.html?

And why are you using them individually, rather than the one blob "scripts.min.js"/"styles.min.css"?

You'd want as few HTTP-requests as possible, so by using them individually, it's theoretical slower. In addition (as a side effect); by not using the minified files, access is blocked by the .htaccess-files (if you're using apache), since they only allow the ".min.js" and ".min.css" files.

**Comment by paolobenve** [comment]
I'm using non-minified css and js files in order to speed up the test fase, I agree that the minified version is better

**Comment by jallakim** [comment]
Ah, I see. That makes sense.
